---
title: Portfolio
timezone: UTC
markdown: kramdown
baseurl: "/portfolio"
url: https://trojan302.github.io/portfolio
exclude:
- README.md
permalink: "/:categories/:title/"
google-analytics:
  id: UA-100001464-1
twitter_username: 
github_username: trojan302
linkedin_username: 
google_plus_username: '105512857669567156066'
facebook_username: devil.rose.666
dribbble_username:

collections:
  portfolios:
    output: true
    permalink: "/:categories/:title/"